2018-07-05 18:12:04.885 +03:00 [Information] Now starting LOS Application XCom Runner ...
2018-07-05 19:17:26.912 +03:00 [Debug] {"$type":"Los.Common.Events.ClientPortal.LenderAddendumCreatedEvent, Los.Common.Events","LoanId":"ccc32bc2-fb59-4893-a0e8-d28958029fe1","Improvements":4.0,"Land":4.0,"Refinance":4.0,"PaidOff":4.0,"ClosingCosts":4.0,"DiscountPoints":4.0,"TotalDueFromBorrower":null,"LoanAmountExludingInsurance":null,"FinancedMortgageInsurance":4.0,"OtherMortgageLoans":4.0,"TotalMortgageLoans":null,"SellerCredits":4.0,"OtherCredits":4.0,"TotalCredits":null,"TotalMortgageAndTotalCredits":null,"TotalCashFromBorrower":null,"Id":"fcf91436-7f0c-4c3a-8023-15d1cb4c7d31","Actor":"00000000-0000-0000-0000-000000000000","AggregateId":"ccc32bc2-fb59-4893-a0e8-d28958029fe1","EntityId":"00000000-0000-0000-0000-000000000000","Version":"","Reason":"00000000-0000-0000-0000-000000000000"}
2018-07-05 19:17:29.327 +03:00 [Error] Error in "ClientPortalXComEventConsumer"
System.Data.SqlClient.SqlException (0x80131904): Cannot attach the file 'C:\IVELIN\PROJECTS\LOS\src\Infrastructure\Los.Application.XCom.Runner\bin\Debug\Los.mdf' as database 'Los'.
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreatePooledConnection(DbConnectionPool pool, DbConnection owningObject, DbConnectionOptions options, DbConnectionPoolKey poolKey, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(Boolean buffer)
   at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.<>c__DisplayClass12_0`2.<Execute>b__0(DbContext c, TState s)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.Execute[TState,TResult](IExecutionStrategy strategy, Func`2 operation, Func`2 verifySucceeded, TState state)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.<_TrackEntities>d__17`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Los.Core.DAL.TrackingDomainRepository`3.GetDbEntities(IEnumerable`1 ids) in C:\IVELIN\PROJECTS\LOS\src\DAL\Los.Core.DAL\TrackingDomainRepository.cs:line 168
   at Los.Core.DAL.TrackingDomainRepository`3.SaveUpdatedEntities(IList`1 updated) in C:\IVELIN\PROJECTS\LOS\src\DAL\Los.Core.DAL\TrackingDomainRepository.cs:line 220
   at Los.Core.DAL.TrackingDomainRepository`3.OnPreSaveChanges(Boolean clearCache) in C:\IVELIN\PROJECTS\LOS\src\DAL\Los.Core.DAL\TrackingDomainRepository.cs:line 196
   at Los.Core.DAL.TrackingDomainRepository`3.OnPreSaveChanges(Object sender, EventArgs eventArgs) in C:\IVELIN\PROJECTS\LOS\src\DAL\Los.Core.DAL\TrackingDomainRepository.cs:line 188
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at Los.Core.DAL.Context.DbContextUnitOfWork`1.<CommitAsync>d__13.MoveNext() in C:\IVELIN\PROJECTS\LOS\src\DAL\Los.Core.DAL\Context\DbContextUnitOfWork.cs:line 73
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Los.Core.Junk.TailUnitOfWork.<CommitAsync>d__19.MoveNext() in C:\IVELIN\PROJECTS\LOS\src\Common\Los.Core\Junk\TailUnitOfWork.cs:line 92
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Los.Application.XCom.Runner.ClientPortalXComEventConsumer.<Consume>d__4.MoveNext() in C:\IVELIN\PROJECTS\LOS\src\Infrastructure\Los.Application.XCom.Runner\ClientPortalXComEventConsumer.cs:line 83
ClientConnectionId:214d757a-4a1d-4ed0-a13d-0adadcce6323
Error Number:1832,State:1,Class:14
2018-07-05 19:17:29.418 +03:00 [Debug] {"$type":"Los.Common.Events.ClientPortal.LenderAddendumCreatedEvent, Los.Common.Events","LoanId":"ccc32bc2-fb59-4893-a0e8-d28958029fe1","Improvements":4.0,"Land":4.0,"Refinance":4.0,"PaidOff":4.0,"ClosingCosts":4.0,"DiscountPoints":4.0,"TotalDueFromBorrower":null,"LoanAmountExludingInsurance":null,"FinancedMortgageInsurance":4.0,"OtherMortgageLoans":4.0,"TotalMortgageLoans":null,"SellerCredits":4.0,"OtherCredits":4.0,"TotalCredits":null,"TotalMortgageAndTotalCredits":null,"TotalCashFromBorrower":null,"Id":"fcf91436-7f0c-4c3a-8023-15d1cb4c7d31","Actor":"00000000-0000-0000-0000-000000000000","AggregateId":"ccc32bc2-fb59-4893-a0e8-d28958029fe1","EntityId":"00000000-0000-0000-0000-000000000000","Version":"","Reason":"00000000-0000-0000-0000-000000000000"}
2018-07-05 19:17:29.564 +03:00 [Error] Error in "ClientPortalXComEventConsumer"
System.Data.SqlClient.SqlException (0x80131904): Cannot attach the file 'C:\IVELIN\PROJECTS\LOS\src\Infrastructure\Los.Application.XCom.Runner\bin\Debug\Los.mdf' as database 'Los'.
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(Boolean buffer)
   at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.<>c__DisplayClass12_0`2.<Execute>b__0(DbContext c, TState s)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.Execute[TState,TResult](IExecutionStrategy strategy, Func`2 operation, Func`2 verifySucceeded, TState state)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.<_TrackEntities>d__17`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Los.Core.DAL.TrackingDomainRepository`3.GetDbEntities(IEnumerable`1 ids) in C:\IVELIN\PROJECTS\LOS\src\DAL\Los.Core.DAL\TrackingDomainRepository.cs:line 168
   at Los.Core.DAL.TrackingDomainRepository`3.SaveUpdatedEntities(IList`1 updated) in C:\IVELIN\PROJECTS\LOS\src\DAL\Los.Core.DAL\TrackingDomainRepository.cs:line 220
   at Los.Core.DAL.TrackingDomainRepository`3.OnPreSaveChanges(Boolean clearCache) in C:\IVELIN\PROJECTS\LOS\src\DAL\Los.Core.DAL\TrackingDomainRepository.cs:line 196
   at Los.Core.DAL.TrackingDomainRepository`3.OnPreSaveChanges(Object sender, EventArgs eventArgs) in C:\IVELIN\PROJECTS\LOS\src\DAL\Los.Core.DAL\TrackingDomainRepository.cs:line 188
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at Los.Core.DAL.Context.DbContextUnitOfWork`1.<CommitAsync>d__13.MoveNext() in C:\IVELIN\PROJECTS\LOS\src\DAL\Los.Core.DAL\Context\DbContextUnitOfWork.cs:line 73
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Los.Core.Junk.TailUnitOfWork.<CommitAsync>d__19.MoveNext() in C:\IVELIN\PROJECTS\LOS\src\Common\Los.Core\Junk\TailUnitOfWork.cs:line 92
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Los.Application.XCom.Runner.ClientPortalXComEventConsumer.<Consume>d__4.MoveNext() in C:\IVELIN\PROJECTS\LOS\src\Infrastructure\Los.Application.XCom.Runner\ClientPortalXComEventConsumer.cs:line 83
ClientConnectionId:214d757a-4a1d-4ed0-a13d-0adadcce6323
Error Number:1832,State:1,Class:14
2018-07-05 19:17:29.605 +03:00 [Debug] {"$type":"Los.Common.Events.ClientPortal.LenderAddendumCreatedEvent, Los.Common.Events","LoanId":"ccc32bc2-fb59-4893-a0e8-d28958029fe1","Improvements":4.0,"Land":4.0,"Refinance":4.0,"PaidOff":4.0,"ClosingCosts":4.0,"DiscountPoints":4.0,"TotalDueFromBorrower":null,"LoanAmountExludingInsurance":null,"FinancedMortgageInsurance":4.0,"OtherMortgageLoans":4.0,"TotalMortgageLoans":null,"SellerCredits":4.0,"OtherCredits":4.0,"TotalCredits":null,"TotalMortgageAndTotalCredits":null,"TotalCashFromBorrower":null,"Id":"fcf91436-7f0c-4c3a-8023-15d1cb4c7d31","Actor":"00000000-0000-0000-0000-000000000000","AggregateId":"ccc32bc2-fb59-4893-a0e8-d28958029fe1","EntityId":"00000000-0000-0000-0000-000000000000","Version":"","Reason":"00000000-0000-0000-0000-000000000000"}
2018-07-05 19:17:29.751 +03:00 [Error] Error in "ClientPortalXComEventConsumer"
System.Data.SqlClient.SqlException (0x80131904): Cannot attach the file 'C:\IVELIN\PROJECTS\LOS\src\Infrastructure\Los.Application.XCom.Runner\bin\Debug\Los.mdf' as database 'Los'.
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(Boolean buffer)
   at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.<>c__DisplayClass12_0`2.<Execute>b__0(DbContext c, TState s)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.Execute[TState,TResult](IExecutionStrategy strategy, Func`2 operation, Func`2 verifySucceeded, TState state)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.<_TrackEntities>d__17`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Los.Core.DAL.TrackingDomainRepository`3.GetDbEntities(IEnumerable`1 ids) in C:\IVELIN\PROJECTS\LOS\src\DAL\Los.Core.DAL\TrackingDomainRepository.cs:line 168
   at Los.Core.DAL.TrackingDomainRepository`3.SaveUpdatedEntities(IList`1 updated) in C:\IVELIN\PROJECTS\LOS\src\DAL\Los.Core.DAL\TrackingDomainRepository.cs:line 220
   at Los.Core.DAL.TrackingDomainRepository`3.OnPreSaveChanges(Boolean clearCache) in C:\IVELIN\PROJECTS\LOS\src\DAL\Los.Core.DAL\TrackingDomainRepository.cs:line 196
   at Los.Core.DAL.TrackingDomainRepository`3.OnPreSaveChanges(Object sender, EventArgs eventArgs) in C:\IVELIN\PROJECTS\LOS\src\DAL\Los.Core.DAL\TrackingDomainRepository.cs:line 188
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at Los.Core.DAL.Context.DbContextUnitOfWork`1.<CommitAsync>d__13.MoveNext() in C:\IVELIN\PROJECTS\LOS\src\DAL\Los.Core.DAL\Context\DbContextUnitOfWork.cs:line 73
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Los.Core.Junk.TailUnitOfWork.<CommitAsync>d__19.MoveNext() in C:\IVELIN\PROJECTS\LOS\src\Common\Los.Core\Junk\TailUnitOfWork.cs:line 92
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Los.Application.XCom.Runner.ClientPortalXComEventConsumer.<Consume>d__4.MoveNext() in C:\IVELIN\PROJECTS\LOS\src\Infrastructure\Los.Application.XCom.Runner\ClientPortalXComEventConsumer.cs:line 83
ClientConnectionId:214d757a-4a1d-4ed0-a13d-0adadcce6323
Error Number:1832,State:1,Class:14
2018-07-05 19:17:29.782 +03:00 [Debug] {"$type":"Los.Common.Events.ClientPortal.LenderAddendumCreatedEvent, Los.Common.Events","LoanId":"ccc32bc2-fb59-4893-a0e8-d28958029fe1","Improvements":4.0,"Land":4.0,"Refinance":4.0,"PaidOff":4.0,"ClosingCosts":4.0,"DiscountPoints":4.0,"TotalDueFromBorrower":null,"LoanAmountExludingInsurance":null,"FinancedMortgageInsurance":4.0,"OtherMortgageLoans":4.0,"TotalMortgageLoans":null,"SellerCredits":4.0,"OtherCredits":4.0,"TotalCredits":null,"TotalMortgageAndTotalCredits":null,"TotalCashFromBorrower":null,"Id":"fcf91436-7f0c-4c3a-8023-15d1cb4c7d31","Actor":"00000000-0000-0000-0000-000000000000","AggregateId":"ccc32bc2-fb59-4893-a0e8-d28958029fe1","EntityId":"00000000-0000-0000-0000-000000000000","Version":"","Reason":"00000000-0000-0000-0000-000000000000"}
2018-07-05 19:17:29.929 +03:00 [Error] Error in "ClientPortalXComEventConsumer"
System.Data.SqlClient.SqlException (0x80131904): Cannot attach the file 'C:\IVELIN\PROJECTS\LOS\src\Infrastructure\Los.Application.XCom.Runner\bin\Debug\Los.mdf' as database 'Los'.
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(Boolean buffer)
   at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.<>c__DisplayClass12_0`2.<Execute>b__0(DbContext c, TState s)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.Execute[TState,TResult](IExecutionStrategy strategy, Func`2 operation, Func`2 verifySucceeded, TState state)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.<_TrackEntities>d__17`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Los.Core.DAL.TrackingDomainRepository`3.GetDbEntities(IEnumerable`1 ids) in C:\IVELIN\PROJECTS\LOS\src\DAL\Los.Core.DAL\TrackingDomainRepository.cs:line 168
   at Los.Core.DAL.TrackingDomainRepository`3.SaveUpdatedEntities(IList`1 updated) in C:\IVELIN\PROJECTS\LOS\src\DAL\Los.Core.DAL\TrackingDomainRepository.cs:line 220
   at Los.Core.DAL.TrackingDomainRepository`3.OnPreSaveChanges(Boolean clearCache) in C:\IVELIN\PROJECTS\LOS\src\DAL\Los.Core.DAL\TrackingDomainRepository.cs:line 196
   at Los.Core.DAL.TrackingDomainRepository`3.OnPreSaveChanges(Object sender, EventArgs eventArgs) in C:\IVELIN\PROJECTS\LOS\src\DAL\Los.Core.DAL\TrackingDomainRepository.cs:line 188
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at Los.Core.DAL.Context.DbContextUnitOfWork`1.<CommitAsync>d__13.MoveNext() in C:\IVELIN\PROJECTS\LOS\src\DAL\Los.Core.DAL\Context\DbContextUnitOfWork.cs:line 73
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Los.Core.Junk.TailUnitOfWork.<CommitAsync>d__19.MoveNext() in C:\IVELIN\PROJECTS\LOS\src\Common\Los.Core\Junk\TailUnitOfWork.cs:line 92
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Los.Application.XCom.Runner.ClientPortalXComEventConsumer.<Consume>d__4.MoveNext() in C:\IVELIN\PROJECTS\LOS\src\Infrastructure\Los.Application.XCom.Runner\ClientPortalXComEventConsumer.cs:line 83
ClientConnectionId:214d757a-4a1d-4ed0-a13d-0adadcce6323
Error Number:1832,State:1,Class:14
2018-07-05 19:17:29.958 +03:00 [Debug] {"$type":"Los.Common.Events.ClientPortal.LenderAddendumCreatedEvent, Los.Common.Events","LoanId":"ccc32bc2-fb59-4893-a0e8-d28958029fe1","Improvements":4.0,"Land":4.0,"Refinance":4.0,"PaidOff":4.0,"ClosingCosts":4.0,"DiscountPoints":4.0,"TotalDueFromBorrower":null,"LoanAmountExludingInsurance":null,"FinancedMortgageInsurance":4.0,"OtherMortgageLoans":4.0,"TotalMortgageLoans":null,"SellerCredits":4.0,"OtherCredits":4.0,"TotalCredits":null,"TotalMortgageAndTotalCredits":null,"TotalCashFromBorrower":null,"Id":"fcf91436-7f0c-4c3a-8023-15d1cb4c7d31","Actor":"00000000-0000-0000-0000-000000000000","AggregateId":"ccc32bc2-fb59-4893-a0e8-d28958029fe1","EntityId":"00000000-0000-0000-0000-000000000000","Version":"","Reason":"00000000-0000-0000-0000-000000000000"}
2018-07-05 19:17:30.077 +03:00 [Error] Error in "ClientPortalXComEventConsumer"
System.Data.SqlClient.SqlException (0x80131904): Cannot attach the file 'C:\IVELIN\PROJECTS\LOS\src\Infrastructure\Los.Application.XCom.Runner\bin\Debug\Los.mdf' as database 'Los'.
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(Boolean buffer)
   at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.<>c__DisplayClass12_0`2.<Execute>b__0(DbContext c, TState s)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.Execute[TState,TResult](IExecutionStrategy strategy, Func`2 operation, Func`2 verifySucceeded, TState state)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.<_TrackEntities>d__17`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Los.Core.DAL.TrackingDomainRepository`3.GetDbEntities(IEnumerable`1 ids) in C:\IVELIN\PROJECTS\LOS\src\DAL\Los.Core.DAL\TrackingDomainRepository.cs:line 168
   at Los.Core.DAL.TrackingDomainRepository`3.SaveUpdatedEntities(IList`1 updated) in C:\IVELIN\PROJECTS\LOS\src\DAL\Los.Core.DAL\TrackingDomainRepository.cs:line 220
   at Los.Core.DAL.TrackingDomainRepository`3.OnPreSaveChanges(Boolean clearCache) in C:\IVELIN\PROJECTS\LOS\src\DAL\Los.Core.DAL\TrackingDomainRepository.cs:line 196
   at Los.Core.DAL.TrackingDomainRepository`3.OnPreSaveChanges(Object sender, EventArgs eventArgs) in C:\IVELIN\PROJECTS\LOS\src\DAL\Los.Core.DAL\TrackingDomainRepository.cs:line 188
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at Los.Core.DAL.Context.DbContextUnitOfWork`1.<CommitAsync>d__13.MoveNext() in C:\IVELIN\PROJECTS\LOS\src\DAL\Los.Core.DAL\Context\DbContextUnitOfWork.cs:line 73
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Los.Core.Junk.TailUnitOfWork.<CommitAsync>d__19.MoveNext() in C:\IVELIN\PROJECTS\LOS\src\Common\Los.Core\Junk\TailUnitOfWork.cs:line 92
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Los.Application.XCom.Runner.ClientPortalXComEventConsumer.<Consume>d__4.MoveNext() in C:\IVELIN\PROJECTS\LOS\src\Infrastructure\Los.Application.XCom.Runner\ClientPortalXComEventConsumer.cs:line 83
ClientConnectionId:214d757a-4a1d-4ed0-a13d-0adadcce6323
Error Number:1832,State:1,Class:14
2018-07-05 19:17:30.106 +03:00 [Debug] {"$type":"Los.Common.Events.ClientPortal.LenderAddendumCreatedEvent, Los.Common.Events","LoanId":"ccc32bc2-fb59-4893-a0e8-d28958029fe1","Improvements":4.0,"Land":4.0,"Refinance":4.0,"PaidOff":4.0,"ClosingCosts":4.0,"DiscountPoints":4.0,"TotalDueFromBorrower":null,"LoanAmountExludingInsurance":null,"FinancedMortgageInsurance":4.0,"OtherMortgageLoans":4.0,"TotalMortgageLoans":null,"SellerCredits":4.0,"OtherCredits":4.0,"TotalCredits":null,"TotalMortgageAndTotalCredits":null,"TotalCashFromBorrower":null,"Id":"fcf91436-7f0c-4c3a-8023-15d1cb4c7d31","Actor":"00000000-0000-0000-0000-000000000000","AggregateId":"ccc32bc2-fb59-4893-a0e8-d28958029fe1","EntityId":"00000000-0000-0000-0000-000000000000","Version":"","Reason":"00000000-0000-0000-0000-000000000000"}
2018-07-05 19:17:30.255 +03:00 [Error] Error in "ClientPortalXComEventConsumer"
System.Data.SqlClient.SqlException (0x80131904): Cannot attach the file 'C:\IVELIN\PROJECTS\LOS\src\Infrastructure\Los.Application.XCom.Runner\bin\Debug\Los.mdf' as database 'Los'.
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.Open(Boolean errorsExpected)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.BufferlessMoveNext(Boolean buffer)
   at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.<>c__DisplayClass12_0`2.<Execute>b__0(DbContext c, TState s)
   at Microsoft.EntityFrameworkCore.Storage.Internal.SqlServerExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.ExecutionStrategyExtensions.Execute[TState,TResult](IExecutionStrategy strategy, Func`2 operation, Func`2 verifySucceeded, TState state)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryingEnumerable`1.Enumerator.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.<_TrackEntities>d__17`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Los.Core.DAL.TrackingDomainRepository`3.GetDbEntities(IEnumerable`1 ids) in C:\IVELIN\PROJECTS\LOS\src\DAL\Los.Core.DAL\TrackingDomainRepository.cs:line 168
   at Los.Core.DAL.TrackingDomainRepository`3.SaveUpdatedEntities(IList`1 updated) in C:\IVELIN\PROJECTS\LOS\src\DAL\Los.Core.DAL\TrackingDomainRepository.cs:line 220
   at Los.Core.DAL.TrackingDomainRepository`3.OnPreSaveChanges(Boolean clearCache) in C:\IVELIN\PROJECTS\LOS\src\DAL\Los.Core.DAL\TrackingDomainRepository.cs:line 196
   at Los.Core.DAL.TrackingDomainRepository`3.OnPreSaveChanges(Object sender, EventArgs eventArgs) in C:\IVELIN\PROJECTS\LOS\src\DAL\Los.Core.DAL\TrackingDomainRepository.cs:line 188
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at Los.Core.DAL.Context.DbContextUnitOfWork`1.<CommitAsync>d__13.MoveNext() in C:\IVELIN\PROJECTS\LOS\src\DAL\Los.Core.DAL\Context\DbContextUnitOfWork.cs:line 73
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Los.Core.Junk.TailUnitOfWork.<CommitAsync>d__19.MoveNext() in C:\IVELIN\PROJECTS\LOS\src\Common\Los.Core\Junk\TailUnitOfWork.cs:line 92
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Los.Application.XCom.Runner.ClientPortalXComEventConsumer.<Consume>d__4.MoveNext() in C:\IVELIN\PROJECTS\LOS\src\Infrastructure\Los.Application.XCom.Runner\ClientPortalXComEventConsumer.cs:line 83
ClientConnectionId:214d757a-4a1d-4ed0-a13d-0adadcce6323
Error Number:1832,State:1,Class:14
2018-07-05 19:17:30.478 +03:00 [Error] (Exception message) Timestamp: 07/05/2018 16:17:30, FaultedMessageId: 3b800000-0daa-1c1b-af08-08d5e292cc6e, FaultId: 3b800000-0daa-1c1b-21d3-08d5e292cea8, Host.Assembly: "Los.Application.XCom.Runner"!
2018-07-05 19:17:30.482 +03:00 [Error] (Exception) Type: "System.Data.SqlClient.SqlException", Source: ".Net SqlClient Data Provider", Message: "Cannot attach the file 'C:\IVELIN\PROJECTS\LOS\src\Infrastructure\Los.Application.XCom.Runner\bin\Debug\Los.mdf' as database 'Los'."!
